name: Misspell fixer
on:
  - push
  #schedule:
    #- cron: '0 0 15 * *'
jobs:
  build:
    #if: github.repository == 'inspircd/inspircd'
    runs-on: ubuntu-latest
    env:
      REF_BRANCH: ${{ github.ref }}
    steps:
    - uses: actions/checkout@v2
    - name : Set a couple env variables
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        echo "ref_branch=${REF_BRANCH//refs\/heads\//}" >> $GITHUB_ENV
    - name: Whitelist some directories and files
      run: |
        echo "\
        ^./.github/workflows
        ^./.mailmap
        ^./vendor
        ^./make/directive.pm:287:atleast
        ^./src/modules/m_disable.cpp:119:existant
        ALLTIME$
        alltime$
        Alltime$\
        " > ${{ runner.workspace }}/inspircd/.misspell-fixer.ignore
    - uses: sobolevn/misspell-fixer-action@master
      with:
        options: '-rvnfuRVD .'
    - uses: peter-evans/create-pull-request@v2.4.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.ref_branch }}+fix-spellings-${{ env.date }}
        author: 'InspIRCd Robot <noreply@inspircd.org>'
        committer: 'InspIRCd Robot <noreply@inspircd.org>'
        commit-message: 'Fixes by misspell-fixer'
        title: 'Typos fix by misspell-fixer'
        reviewers: 'genius3000'
