name: misspell
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "^./.github/workflows/misspell-fixer.yml" > ${{ runner.workspace }}/inspircd/.misspell-fixer.ignore
        echo "^./vendor" >> ${{ runner.workspace }}/inspircd/.misspell-fixer.ignore
        echo "^./make/directive.pm:287:atleast" >> ${{ runner.workspace }}/inspircd/.misspell-fixer.ignore
        echo "^./src/modules/m_disable:119:fakenonexistant" >> ${{ runner.workspace }}/inspircd/.misspell-fixer.ignore
    - uses: sobolevn/misspell-fixer-action@master
    - uses: peter-evans/create-pull-request@v2.4.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Fixes by misspell-fixer'
        title: 'Typos fix by misspell-fixer'
